steps:
  - name: question-goals
    script: scripts/define_goals.sh
    input_schema: schemas/goals.input.json
    output_schema: schemas/goals.output.json
  - name: prepare-data
    script: scripts/prepare_data.py
    input_schema: schemas/data.input.json
    output_schema: schemas/data.output.json
  - name: run-backtest
    script: scripts/run_backtest.py
    input_schema: schemas/backtest.input.json
    output_schema: schemas/backtest.output.json
  - name: compute-kpi
    script: scripts/report_kpi.py
    input_schema: schemas/kpi.input.json
    output_schema: schemas/kpi.output.json
  - name: risk-checks
    script: scripts/risk_checks.py
    input_schema: schemas/risk.input.json
    output_schema: schemas/risk.output.json
  - name: archive-review
    script: scripts/archive_review.sh
    input_schema: schemas/archive.input.json
    output_schema: schemas/archive.output.json
