steps:
  - name: draft-requirements
    script: scripts/draft_spec.sh
    input_schema: schemas/requirements.input.json
    output_schema: schemas/requirements.output.json
  - name: design-doc
    script: scripts/generate_design.sh
    input_schema: schemas/design.input.json
    output_schema: schemas/design.output.json
  - name: impl-plan
    script: scripts/generate_tasks.py
    input_schema: schemas/tasks.input.json
    output_schema: schemas/tasks.output.json
