steps:
  - name: init-aliases
    script: scripts/alias_setup.sh
    description: 初始化 alias 配置（添加到 shell 配置文件）
    input_schema: schemas/init.input.json
    output_schema: schemas/init.output.json

  - name: switch-alias
    script: scripts/switch_alias.sh
    description: 切换到指定的 alias（glm/claude/cc）
    input_schema: schemas/switch.input.json
    output_schema: schemas/switch.output.json

  - name: verify-config
    script: scripts/verify_config.sh
    description: 验证当前配置是否正确
    input_schema: schemas/verify.input.json
    output_schema: schemas/verify.output.json

  - name: show-status
    script: scripts/show_status.sh
    description: 显示当前配置状态
    input_schema: schemas/status.input.json
    output_schema: schemas/status.output.json
